"""Smoke test. Do not edit this file.

It also shows how to call the reference module: named arguments, and the
result compared with a plain string.
"""

from reference import reservation_disposition

GRACE_MINUTES = 1  # a configured value for this smoke test only, not policy


def test_reference_module_imports_and_uses_configured_policy() -> None:
    state = reservation_disposition(
        minutes_after_start=0,
        grace_minutes=GRACE_MINUTES,
        checked_in=False,
    )
    assert state == "held"
